name: ci

on:
  push:
    branches:
      - "main"
  workflow_dispatch:  # 允許手動執行 Workflow

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud  # 使用 Docker Build Cloud 來建置映像
          endpoint: "chenggg/liteon"  # 指定 Docker Build Cloud 端點
          install: true

      - name: Build and push Docker image (x86_64 & armv7)
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm/v7
          tags: |
            ${{ vars.DOCKER_USER }}/ovenview-app:latest
            ${{ vars.DOCKER_USER }}/ovenview-app:armv7
          push: true
          build-args: |
            BUILD_ENV=production
          cache-from: type=gha
          cache-to: type=gha,mode=max

